services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=phuonglth
      - MONGO_INITDB_ROOT_PASSWORD=phuonglth
  mongo-express:
    image: mongo-express:1.0.2-20
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=phuonglth
      - ME_CONFIG_MONGODB_ADMINPASSWORD=phuonglth
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo: {}